# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            exclude_types: [svg]
          - id: end-of-file-fixer
            exclude_types: [svg]
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pycqa/isort
      rev: 5.11.2
      hooks:
          - id: isort
            args: [--profile, black]
            types: [python]
    - repo: https://github.com/ambv/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.5.3
      hooks:
        - id: nbqa-black
          # additional_dependencies: [jupytext]  # optional, only if you're using Jupytext
        - id: nbqa-pyupgrade
          args: ["--py37-plus"]
        - id: nbqa-isort
          # args: ["--float-to-top"]
          args: [--profile, black]
