[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-vv",
    "--strict-markers",
    "--strict-config",
    "--cov=causalpy",
    "--cov-report=term-missing",
]
testpaths = "causalpy/tests"
markers = [
    "integration: mark as an integration test.",
    "slow: mark test as slow.",
    ]
